import { companies, searchCompanies } from './companies/catalog.js';
import { createMarketGlobe } from './globe/marketGlobe.js';
import './ui/terminal.css';
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=companies[0],globe=null,activeTab='assets';
$('app').innerHTML=`
<header class="app-header"><div class="brand"><img src="/marketeye.svg" alt=""/>Market<span>Eye</span></div><div class="nav-label">Intelligence workspace</div><div class="search"><label class="sr-only" for="company-search">Search company or ticker</label><input id="company-search" placeholder="Search company or ticker…" autocomplete="off"/><div id="search-results" class="search-results"></div></div><div class="header-meta mono">PHYSICAL-WORLD INTELLIGENCE</div></header>
<main class="workspace"><aside class="left-rail" aria-label="Watchlist and signals"><section class="rail-section"><div class="section-title"><span class="eyebrow">Watchlist</span><span class="count">03</span></div><div id="watchlist"></div></section><section class="rail-section"><div class="section-title"><span class="eyebrow">World signals</span><span id="signal-count" class="count">—</span></div><div id="signals"><p class="empty">Connecting to public event sources…</p></div><button id="refresh" class="secondary">↻ Refresh sources</button></section><section class="rail-section"><div class="section-title"><span class="eyebrow">Map layers</span></div><label class="layer"><input type="checkbox" data-layer="assets" checked/> Company footprint</label><label class="layer"><input type="checkbox" data-layer="paths" checked/> Dependency paths</label><label class="layer"><input type="checkbox" data-layer="signals" checked/> World events</label><div id="extra-layers"></div></section><section class="rail-section"><div class="eyebrow">Evidence, before inference</div><p class="empty">Physical proximity identifies potential exposure. It does not confirm disruption.</p><button id="methodology" class="secondary">Scoring & methodology ↗</button></section></aside>
<section class="globe-area" aria-label="Interactive company exposure globe"><div id="cesiumContainer"></div><div class="globe-top"><div class="eyebrow">Global exposure / <span id="map-ticker">NVDA</span></div><h1 id="map-heading">The semiconductor network</h1><small>Explore the physical world behind the company.</small></div><div class="globe-tools"><button id="reset-view">◎ Overview</button><button id="basemap">Satellite / Street</button></div><div class="map-caption"><div class="eyebrow" id="region-caption">Taiwan · Focus region</div><strong id="map-subtitle">A critical link in the compute economy.</strong><div class="legend"><span><i></i> Company / supplier</span><span><i class="amber"></i> World event</span></div></div><section class="impact-dock"><span class="eyebrow">Impact path</span><span id="impact-status" class="impact-status">STRUCTURAL DEPENDENCY</span><div id="impact-chain" class="impact-chain"></div></section><div id="cesium-credits"></div></section>
<aside class="right-rail" aria-label="Company intelligence"><div id="company-head" class="company-head"></div><section class="score-card"><div class="eyebrow">Event-linked exposure</div><div class="score-line"><div class="score" id="score">— <span>/ 100</span></div><span id="score-badge" class="badge">CONNECTING</span></div><div class="meter"><div id="score-meter" style="width:0%"></div></div><p id="score-explanation">Waiting for source coverage. This is a screening score, not a loss forecast.</p></section><section class="rail-section" style="padding-top:0"><div class="eyebrow">Key dependencies</div><div id="dependencies"></div><button id="investigate" class="primary">Investigate exposure ↗</button><button id="export-brief" class="secondary">↓ Export intelligence brief</button></section><div class="tabbar" role="tablist" aria-label="Company details"><button class="active" data-tab="assets" role="tab" aria-selected="true">Assets</button><button data-tab="evidence" role="tab" aria-selected="false">Evidence</button><button data-tab="analyst" role="tab" aria-selected="false">Analyst</button></div><div id="tab-content" class="tab-content" role="tabpanel"></div></aside></main>
<footer class="statusbar"><span><i class="dot"></i>MarketEye</span><span id="source-status">Sources connecting</span><span id="map-status">Globe initializing</span><span>INFORMATIONAL ANALYSIS · NOT INVESTMENT ADVICE</span></footer>
<dialog id="detail-dialog" class="dialog"><header><h2 id="dialog-title"></h2><button id="close-dialog" aria-label="Close dialog">✕</button></header><div id="dialog-content"></div></dialog>`;
function showDialog(title,html){$('dialog-title').textContent=title;$('dialog-content').innerHTML=html;if(!$('detail-dialog').open)$('detail-dialog').showModal();}
$('close-dialog').onclick=()=>$('detail-dialog').close();
function renderTab(){
  $('tab-content').innerHTML=activeTab==='assets'?selected.locations.map(l=>`<button class="asset-row" data-location="${l.id}"><strong>${esc(l.name)} ↗</strong><small>${esc(l.region)} · ${esc(l.type)} · ${l.relationship==='context-only'?'Context only':l.relationship==='supplier-context'?'Allocation unknown':'Documented footprint'}</small></button>`).join(''):activeTab==='evidence'?`<p class="empty">Reviewed ${selected.reviewedAt}. ${esc(selected.coordinatePolicy)}</p>${[...selected.suppliers,...selected.locations].map(r=>`<div class="evidence"><p>${esc(r.statement||r.description)}</p><a href="${esc(r.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(r.source)} ↗</a></div>`).join('')}<h3>Unknowns</h3>${selected.unknowns.map(u=>`<p class="empty">• ${esc(u)}</p>`).join('')}`:'<p class="empty">Structured analyst tools are being connected.</p>';
  document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>selectLocation(selected.locations.find(l=>l.id===b.dataset.location)));
}
function selectLocation(l){globe?.flyTo(l);showDialog(l.name,`<span class="badge">${esc(l.relationship)}</span><p style="margin-top:16px">${esc(l.description)}</p><p class="muted">Approximate campus / regional coordinates. Evidence confidence: ${Math.round(l.confidence*100)}%.</p><a href="${esc(l.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(l.source)} ↗</a>`);}
function renderCompany(){
  $('watchlist').innerHTML=companies.map(c=>`<button class="watch ${c===selected?'active':''}" data-company="${c.ticker}"><div class="watch-top"><span class="ticker">${c.ticker}</span><span style="color:${c.color}">↗</span></div><small>${c.name} · ${c.sector}</small></button>`).join('');
  document.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>selectCompany(b.dataset.company));
  $('company-head').innerHTML=`<div class="company-badge" style="color:${selected.color}">${selected.ticker.slice(0,2)}</div><h2>${selected.name}</h2><small class="company-sub mono">${selected.exchange}: ${selected.ticker} / ${selected.sector.toUpperCase()}</small><p class="thesis">${selected.thesis}</p>`;
  $('dependencies').innerHTML=selected.regions.map(r=>`<div class="dependency"><strong>${r.name}</strong><small>${r.role}</small><div class="eyebrow">${r.level}</div></div>`).join('');
  $('map-ticker').textContent=selected.ticker;$('map-heading').textContent=selected.ticker==='TSLA'?'The manufacturing footprint':'The semiconductor network';$('region-caption').textContent=selected.regions[0].name+' · Focus region';
  $('map-subtitle').textContent=selected.ticker==='NVDA'?'A critical link in the compute economy.':selected.ticker==='AAPL'?'The geography behind the devices.':'Where manufacturing meets the world.';
  $('impact-chain').innerHTML=[['Region',selected.regions[0].name],['Dependency',selected.dependencies[0].name],['Company',selected.name]].map(([type,label])=>`<div class="impact-node"><small>${type}</small>${label}</div>`).join('<span class="arrow">→</span>');renderTab();
}
function selectCompany(ticker){selected=companies.find(c=>c.ticker===ticker)||selected;renderCompany();globe?.showCompany(selected);globe?.flyTo(selected.focus);$('search-results').innerHTML='';$('company-search').value='';}
$('company-search').oninput=e=>{$('search-results').innerHTML=searchCompanies(e.target.value).map(c=>`<button data-result="${c.ticker}">${c.ticker} · ${c.name}</button>`).join('')||'<p class="empty">No match. Coverage: NVDA, AAPL, TSLA.</p>';document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>selectCompany(b.dataset.result));};
$('company-search').onkeydown=e=>{if(e.key==='Enter'){const match=searchCompanies(e.target.value)[0];if(match)selectCompany(match.ticker);}if(e.key==='Escape')$('search-results').innerHTML='';};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-selected',String(t===b));});renderTab();});
document.querySelectorAll('[data-layer]').forEach(c=>c.onchange=()=>globe?.toggle(c.dataset.layer,c.checked));
$('reset-view').onclick=()=>globe?.flyTo(selected.focus);$('basemap').onclick=()=>globe?.maps.setStack(globe.maps.getState().activeId==='osm'?'esri-imagery':'osm');
renderCompany();
try{globe=await createMarketGlobe(({kind,record})=>kind==='location'?selectLocation(record):null,message=>$('map-status').textContent=message);globe.showCompany(selected);globe.flyTo(selected.focus,1600000,0);}
catch(error){$('map-status').textContent='Globe unavailable';const notice=document.createElement('div');notice.className='globe-error';notice.textContent=`The globe could not start: ${error.message}. Company evidence remains available. Enable WebGL and reload to explore the map.`;document.querySelector('.globe-area').append(notice);}
